// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwbXsn3_YVmX8hra2GdOYt55BwDHMO7k',
    appId: '1:810720453883:web:0353a9ccf05e9a773dbc5e',
    messagingSenderId: '810720453883',
    projectId: 'ayeyo-37ba2',
    authDomain: 'ayeyo-37ba2.firebaseapp.com',
    storageBucket: 'ayeyo-37ba2.firebasestorage.app',
    measurementId: 'G-FWCM674X23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbL9zSQkeaNagAykXaGvNdejSmmPAJvzs',
    appId: '1:810720453883:android:2ed1d90f1632f7d43dbc5e',
    messagingSenderId: '810720453883',
    projectId: 'ayeyo-37ba2',
    storageBucket: 'ayeyo-37ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgT_Np0UNbKWySEjZ6JHIAdw_UjWQnn2M',
    appId: '1:810720453883:ios:5eee3b3de70800ec3dbc5e',
    messagingSenderId: '810720453883',
    projectId: 'ayeyo-37ba2',
    storageBucket: 'ayeyo-37ba2.firebasestorage.app',
    iosBundleId: 'com.example.ayeyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgT_Np0UNbKWySEjZ6JHIAdw_UjWQnn2M',
    appId: '1:810720453883:ios:5eee3b3de70800ec3dbc5e',
    messagingSenderId: '810720453883',
    projectId: 'ayeyo-37ba2',
    storageBucket: 'ayeyo-37ba2.firebasestorage.app',
    iosBundleId: 'com.example.ayeyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtwbXsn3_YVmX8hra2GdOYt55BwDHMO7k',
    appId: '1:810720453883:web:57b99699f35521eb3dbc5e',
    messagingSenderId: '810720453883',
    projectId: 'ayeyo-37ba2',
    authDomain: 'ayeyo-37ba2.firebaseapp.com',
    storageBucket: 'ayeyo-37ba2.firebasestorage.app',
    measurementId: 'G-CDG4LYS418',
  );
}
